name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # we find that CPU/memory limits are less often exceeded using this 
    # specific version of Ubuntu
    runs-on: ubuntu-20.04

    #runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: pip installation
    # test pip installation first (much faster than conda)
      run: |
         pip install --upgrade pip
         pip install -e .
    - name: Basic tests
      run: |
         python tests/check_import.py
         python tests/check_entry_points.py
         bash tests/check_examples.bash
    - name: Advanced tests
      run: |
         bash data/examples/unpack.bash
         bash data/tests/unpack.bash
         python tests/benchmark_cap_vs_mtuq.py --no_figures
         python tests/test_grid_search_mt.py --no_figures
         python tests/test_grid_search_mt_depth.py --no_figures
         python tests/test_greens_SPECFEM3D_SAC.py --no_figures
         python tests/test_time_shifts.py --no_figures

    # unfortunately, these Conda installation tests exceed the resource limits
    # for GitHub workflows
    # (https://github.com/actions/runner-images/issues/6680)
    # (https://github.com/conda/conda/issues/8650)
    #- name: conda installation
    #  timeout-minutes: 60
    #  run: |
    #     bash tests/conda_install.bash

